[tool.poetry]
name = "cmini"
version = "0.1.0"
description = ""
authors = ["Apsu <apsu@propter.net>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
"discord.py" = "^2.7"
aiohttp = "^3.11"
more-itertools = "^10.0"
jellyfish = "^1.1"
humanize = "^4.12"
requests = "^2.32"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
